favicon: null
name: emota
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#fffefe'
  lightness: 0.9375
typography_spectrum: 0.49087
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5860214
analytics:
  twitter: null
  google: null
  facebook: null
