name: emota
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49087
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffefe'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
