name: emota
favicon: null
layout_spectrum: 0.6698980194050819
typography_spectrum: 0.31521804560907185
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5299406689591706
  lightness: 0.8642475088126957
  saturation: 0.4390309229493141
  rhythmicContrast: 0.8743727516848594
purpose: []
